version: '2'
services:
  consul:
    image: consul:latest
    container_name: consul
    network_mode: host
    environment:
      CONSUL_BIND_INTERFACE: "wlp4s0"
      CONSUL_LOCAL_CONFIG: "{\"ports\": {\"dns\": 53}, \"recursors\": [\"8.8.8.8\"]}"
      CONSUL_ALLOW_PRIVILEGED_PORTS: "true"
    labels:
      SERVICE_IGNORE: "true"

  registrator:
    image: gliderlabs/registrator:latest
    container_name: registrator
    privileged: true
    network_mode: host
    depends_on:
      - consul
    command: consul://localhost:8500
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
  
  #dns:
  #  image: andyshinn/dnsmasq:latest
  #  container_name: dnsmasq
  #  command: -S /consul/127.0.0.1#8600
  #  network_mode: host
  #  cap_add:  
  #    - NET_ADMIN
  
  proxy:
    image: traefik
    container_name: proxy
    command: --web --consul --consul.endpoint=localhost:8500 --consulcatalog.endpoint=localhost:8500  --logLevel=DEBUG
    network_mode: host
    depends_on:
      - consul
    dns: "172.17.0.1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml
    labels:
      SERVICE_IGNORE: "true"

  gogs:
    image: gogs/gogs:0.11.19
    container_name: gogs
    depends_on:
      - registrator
    network_mode: host
    ports:
      - "3000:3000"
    environment:
      - SERVICE_NAME=gogs
    dns: "172.17.0.1"
    volumes:
      - /data"
    labels:
      SERVICE_TAGS: "traefik.frontend.rule=Host:gogs.service.consul"

  gogs-database:
    image: postgres:9.1
    container_name: gogs-database
    depends_on:
      - registrator
    network_mode: host
    ports:
      - "5432:5432"
    environment:
      - SERVICE_NAME=gogs-database
      - POSTGRES_USER=gogs
      - POSTGRES_PASSWORD=gogs
    dns: "172.17.0.1"
    volumes:
      - /var/lib/postgresql/data
    labels:
      SERVICE_TAGS: "traefik.frontend.rule=Host:gogs-database.service.consul"

  drone-server:
    image: drone/drone:0.7
    container_name: drone
    depends_on:
      - registrator
    network_mode: host
    ports:
      - "8000:8000"
    environment:
      - SERVICE_NAME=drone
    dns: "172.17.0.1"
    environment:
      - DRONE_SECRET=gogsdronecompose
      - DRONE_OPEN=true
      - DRONE_HOST=http://drone.service.consul
      - DRONE_GOGS=true
      - DRONE_GOGS_URL=http://gogs.service.consul
      - DEBUG=true
    volumes:
      - /var/lib/drone
    labels:
      SERVICE_TAGS: "traefik.frontend.rule=Host:drone.service.consul"
    
  drone-agent:
    image: drone/drone:0.7
    container_name: drone-agent
    command: agent
    depends_on:
      - registrator
      - drone-server
    dns: "172.17.0.1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_SERVER=ws://drone.service.consul/ws/broker
      - DRONE_SECRET=gogsdronecompose
    labels:
      SERVICE_IGNORE: "true"

